version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration:
- Test
- Release
matrix:
  fast_finish: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  SHFBROOT: C:\projects\swissarmylib\EWSoftware.SHFB.2017.5.15.0\tools\
  SHFB_COMPONENTS: C:\projects\swissarmylib\EWSoftware.SHFB.NETFramework.4.7\tools\
before_build:
- cmd: >-
    nuget restore Archon.SwissArmyLib.sln
    
    nuget install EWSoftware.SHFB -Version 2017.5.15

    nuget install EWSoftware.SHFB.NETFramework -Version 4.7.0
build:
  project: Archon.SwissArmyLib.sln
  verbosity: minimal
after_build:
- ps: >-
    if ($env:CONFIGURATION -ne "Test") {

    jar -cMf "./SwissArmyLib-${env:APPVEYOR_BUILD_VERSION}.zip" -C "./bin/${env:CONFIGURATION}" .

    jar -cMf "./SwissArmyLib-${env:APPVEYOR_BUILD_VERSION}-Docs.zip" -C ./Documentation/Help .

    }
test:
  assemblies:
    only:
    - Archon.SwissArmyLibTests\bin\Test\*
artifacts:
- path: SwissArmyLib-$(APPVEYOR_BUILD_VERSION).zip
  name: Binaries
- path: SwissArmyLib-$(APPVEYOR_BUILD_VERSION)-Docs.zip
  name: Docs
deploy:
- provider: BinTray
  username: phault
  api_key:
    secure: ZnJnGS3aRZB0wC9Il38Y/YQLVJnZUhLUkoMh9x8tIGnJXfcjYkCuIBfPokeERMeK
  subject: phault
  repo: SwissArmyLib
  package: development
  publish: true
  override: true
  on:
    branch: master
    CONFIGURATION: Release