using System;
using System.Collections.Generic;
using Archon.SwissArmyLib.Collections;
using UnityEngine;

namespace Archon.SwissArmyLib.Events
{
    /// <summary>
    /// A simple event system that uses interfaces instead of delegates to avoid the garbage generated by them.
    /// 
    /// This version is for parameterless events. 
    /// See <see cref="EventSystem{T}"/> if you need to send data with the event.
    /// 
    /// Events are differentiated by an integer. You are expected to create constants to define your events.
    /// </summary>
    public static class EventSystem
    {
        private static readonly Dictionary<int, PrioritizedList<IEventListener>> EventListeners = new Dictionary<int, PrioritizedList<IEventListener>>();

        /// <summary>
        /// Invokes an event.
        /// </summary>
        /// <param name="eventId">The id of the event.</param>
        public static void Invoke(int eventId)
        {
            PrioritizedList<IEventListener> listeners;
            if (EventListeners.TryGetValue(eventId, out listeners))
            {
                for (var i = 0; i < listeners.Count; i++)
                {
                    // gotta wrap it up so one guy doesn't spoil it for everyone
                    try
                    {
                        listeners[i].OnEvent(eventId);
                    }
                    catch (Exception e)
                    {
                        Debug.LogError(e.Message);
                    }
                }
            }
        }

        /// <summary>
        /// Adds a listener for an event.
        /// </summary>
        /// <param name="eventId">The id of the event.</param>
        /// <param name="listener">The listener to be called.</param>
        /// <param name="priority">The priority of the listener which affects the order which listeners are called in.</param>
        public static void AddListener(int eventId, IEventListener listener, int priority = 0)
        {
            PrioritizedList<IEventListener> listeners;
            if (!EventListeners.TryGetValue(eventId, out listeners))
                EventListeners[eventId] = listeners = new PrioritizedList<IEventListener>();

            listeners.Add(listener, priority);
        }

        /// <summary>
        /// Removes a listener for an event.
        /// </summary>
        /// <param name="eventId">The id of the event.</param>
        /// <param name="listener">The listener to remove.</param>
        public static void RemoveListener(int eventId, IEventListener listener)
        {
            PrioritizedList<IEventListener> listeners;
            if (EventListeners.TryGetValue(eventId, out listeners))
                listeners.Remove(listener);
        }

        /// <summary>
        /// Clears all listeners for all events.
        /// </summary>
        public static void Clear()
        {
            foreach (var listenerList in EventListeners.Values)
                listenerList.Clear();
        }

        /// <summary>
        /// Clears all listeners for a single event.
        /// </summary>
        /// <param name="eventId">The id of the event.</param>
        public static void Clear(int eventId)
        {
            PrioritizedList<IEventListener> listeners;
            if (EventListeners.TryGetValue(eventId, out listeners))
                listeners.Clear();
        }
    }

    /// <summary>
    /// A simple event system that uses interfaces instead of delegates to avoid the garbage generated by them.
    /// 
    /// This version is for events with args. 
    /// See <see cref="EventSystem"/> if you don't need to send data with the event.
    /// 
    /// Events are differentiated by an integer. You are expected to create constants to define your events.
    /// </summary>
    public static class EventSystem<T>
    {
        private static readonly Dictionary<int, PrioritizedList<IEventListener<T>>> EventListeners = new Dictionary<int, PrioritizedList<IEventListener<T>>>();

        /// <summary>
        /// Invokes an event.
        /// </summary>
        /// <param name="eventId">The id of the event.</param>
        /// <param name="args">The event args.</param>
        public static void Invoke(int eventId, T args)
        {
            PrioritizedList<IEventListener<T>> listeners;
            if (EventListeners.TryGetValue(eventId, out listeners))
            {
                for (var i = 0; i < listeners.Count; i++)
                {
                    // gotta wrap it up so one guy doesn't spoil it for everyone
                    try
                    {
                        listeners[i].OnEvent(eventId, args);
                    }
                    catch (Exception e)
                    {
                        Debug.LogError(e.Message);
                    }
                }
            }
        }

        /// <summary>
        /// Adds a listener for an event.
        /// </summary>
        /// <param name="eventId">The id of the event.</param>
        /// <param name="listener">The listener to be called.</param>
        /// <param name="priority">The priority of the listener which affects the order which listeners are called in.</param>
        public static void AddListener(int eventId, IEventListener<T> listener, int priority = 0)
        {
            PrioritizedList<IEventListener<T>> listeners;
            if (!EventListeners.TryGetValue(eventId, out listeners))
                EventListeners[eventId] = listeners = new PrioritizedList<IEventListener<T>>();

            listeners.Add(listener, priority);
        }

        /// <summary>
        /// Removes a listener for an event.
        /// </summary>
        /// <param name="eventId">The id of the event.</param>
        /// <param name="listener">The listener to remove.</param>
        public static void RemoveListener(int eventId, IEventListener<T> listener)
        {
            PrioritizedList<IEventListener<T>> listeners;
            if (EventListeners.TryGetValue(eventId, out listeners))
                listeners.Remove(listener);
        }

        /// <summary>
        /// Clears all listeners for all events.
        /// </summary>
        public static void Clear()
        {
            foreach (var listenerList in EventListeners.Values)
                listenerList.Clear();
        }

        /// <summary>
        /// Clears all listeners for a single event.
        /// </summary>
        /// <param name="eventId">The id of the event.</param>
        public static void Clear(int eventId)
        {
            PrioritizedList<IEventListener<T>> listeners;
            if (EventListeners.TryGetValue(eventId, out listeners))
                listeners.Clear();
        }
    }

    /// <summary>
    /// Defines a method to be used for event callbacks.
    /// </summary>
    public interface IEventListener
    {
        /// <summary>
        /// Called when an event is invoked.
        /// </summary>
        /// <param name="eventId">The id of the event.</param>
        void OnEvent(int eventId);
    }

    /// <summary>
    /// Defines a method to be used for event callbacks with a parameter of type <typeparamref name="TArgs"/>.
    /// </summary>
    /// <typeparam name="TArgs"></typeparam>
    public interface IEventListener<in TArgs>
    {
        /// <summary>
        /// Called when an event is invoked.
        /// </summary>
        /// <param name="eventId">The id of the event.</param>
        /// <param name="args">The args for the event.</param>
        void OnEvent(int eventId, TArgs args);
    }
}
